## K- Nearest Neighbors (KNN) Algorithm from scratch
### Author: Sayali Kudale

In [20]:

# Importing the required libraries
import pandas as pd 
import numpy as np
import scipy.io
from math import sqrt
import time 
from sklearn.metrics import accuracy_score, classification_report 

In [21]:
#Data loading
mat = scipy.io.loadmat('Data/USPS_all.mat')

# Data splitting into training and testing

train_X=mat['fea'][:7291]
test_X=mat['fea'][-2007:]
train_Y=mat['gnd'][:7291]
test_Y=mat['gnd'][-2007:]


## Simple KNN algorithm

In [13]:
# Euclidian distance calculation function
# This method computes the euclidian distance between test row and train row 

def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [22]:
# Locate the most similar neighbors
# This method finds the distance test data point  from  each point in train data
#          using euclidian distance formula
# Distances are sorted in ascending order 
# The top K closest train features data points from test row are returned 
# Input param : 
# train_X - training feature data 
# test_row - test data row
# num_neighbors - number of neighbours 

def get_neighbors(train_X, test_row, num_neighbors):
    distances = list()
    
    for idx,train_row in enumerate(train_X):
        dist = euclidean_distance(test_row, train_row)
        distances.append((idx, dist))
        
    distances.sort(key=lambda tup: tup[1])
    
    neighbors = list()
    
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors

In [23]:

# Make a classification prediction with neighbors
# This method gets the top K closest feature dataset from test data row
# Gets the corrosponding lables of feature set 
# returns the label which has maximum occurance
# Input param : 
# train_X - training feature data 
# train_dec - training label data
# test_row - test data row
# num_neighbors - number of neighbours 

def predict_classification(train_X,train_dec, test_row, num_neighbors):
    neighbors = get_neighbors(train_X, test_row, num_neighbors)
    output_values=list()
    for val in neighbors:
        output_values.append(train_dec.iloc[val].values[0])
    prediction = max(set(output_values), key=output_values.count)
    return prediction

In [24]:
# This method performs k-nearest neighbour algorithm 
# Iterate through allthe test data set and pass it to the predict_classification method
# It gets the list of predicted values for all the test data set
# Input param : 
# train_X - training feature data 
# train_dec - training label data
# test_X- test data set
# num_neighbors - number of neighbours 

def k_nearest_neighbors(train_X,train_dec, test_X, num_neighbors):
    predictions = list()
    for row in test_X:
        output = predict_classification(train_X,train_dec, row, num_neighbors)
        predictions.append(output)
    return(predictions)

In [25]:
# This method Calculate accuracy percentage
# By comparing the correct values with the predicted values and then calculating the percentage 
# Input param : 
# actual : actual labels of testdata
# predicted : predicted labels of test data
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0

In [41]:
# Call  to the k_nearest_neighbors
# value of k =3 
trainStart = time.time()

predictedKnn_3 = k_nearest_neighbors(train_X,pd.DataFrame(train_Y), test_X, 3)

trainEnd = time.time()

print("Training time : ", trainEnd-trainStart)

accuracy = accuracy_metric(test_Y, predictedKnn_3)

print('Accuracy when k=3 : %s' % accuracy)

classsification_report=classification_report(pd.DataFrame(test_Y), predictedKnn_3)

print('Classification report : \n',classsification_report)

Training time :  2487.6575088500977
Accuracy when k=3 : 94.76831091180867
Classification report : 
              precision    recall  f1-score   support

          1       0.95      0.99      0.97       359
          2       0.99      0.97      0.98       264
          3       0.95      0.92      0.94       198
          4       0.97      0.92      0.94       166
          5       0.94      0.90      0.92       200
          6       0.92      0.91      0.92       160
          7       0.98      0.95      0.96       170
          8       0.96      0.95      0.96       147
          9       0.93      0.94      0.93       166
         10       0.88      0.98      0.93       177

avg / total       0.95      0.95      0.95      2007



In [58]:
from sklearn.metrics import confusion_matrix  
cm_k3= confusion_matrix(test_Y, predictedKnn_3)  
print("Confusion Matrix for k=3 \n",cm_k3)

Confusion Matrix for k=3 
 [[355   0   2   0   0   0   0   1   0   1]
 [  0 256   0   0   4   0   2   1   1   0]
 [  6   0 183   1   0   1   0   2   5   0]
 [  2   0   1 152   0   8   0   1   1   1]
 [  0   2   2   0 179   0   2   1   1  13]
 [  3   0   1   3   0 146   0   0   3   4]
 [  3   0   3   0   1   1 162   0   0   0]
 [  0   0   1   0   5   0   0 140   0   1]
 [  3   0   0   1   0   2   0   0 156   4]
 [  1   0   0   0   2   0   0   0   1 173]]


In [42]:

# creating dataframe to compare the actual vs the predicted values 
df_actual_vs_pre=pd.DataFrame(test_Y)
df_actual_vs_pre["predicted_K3"]=np.array(predictedKnn_3)

In [ ]:
# Call  to the k_nearest_neighbors
# value of k =5 
trainStart = time.time()

predictedKnn_5 = k_nearest_neighbors(train_X,pd.DataFrame(train_Y), test_X, 5)

trainEnd = time.time()

print("Training time : ", trainEnd-trainStart)
df_actual_vs_pre["predicted_K5"]=np.array(predictedKnn_5)


accuracy = accuracy_metric(test_Y, predictedKnn_5)
print('Accuracy when k=5 : %s' % accuracy)

classsification_report=classification_report(pd.DataFrame(test_Y), predictedKnn_5)

print('Classification report : \n',classsification_report)

Training time :  5917.385703086853
Accuracy when k=5 : 94.86796213253612
Classification report : 
              precision    recall  f1-score   support

          1       0.96      0.99      0.98       359
          2       0.99      0.98      0.99       264
          3       0.94      0.92      0.93       198
          4       0.96      0.90      0.93       166
          5       0.92      0.90      0.91       200
          6       0.94      0.90      0.92       160
          7       0.97      0.96      0.96       170
          8       0.96      0.96      0.96       147
          9       0.94      0.95      0.94       166
         10       0.89      0.98      0.93       177

avg / total       0.95      0.95      0.95      2007



In [59]:
cm_k5= confusion_matrix(test_Y, predictedKnn_5)  
print("Confusion Matrix for k=5 \n",cm_k5)

Confusion Matrix for k=5 
 [[355   0   2   0   1   0   0   0   0   1]
 [  0 259   0   0   3   0   2   0   0   0]
 [  6   0 183   1   2   0   1   2   3   0]
 [  1   0   1 150   0   8   0   2   1   3]
 [  0   2   3   0 179   0   2   2   1  11]
 [  3   0   2   4   0 144   0   0   3   4]
 [  1   0   3   0   2   0 163   0   1   0]
 [  0   0   1   0   5   0   0 141   0   0]
 [  2   0   0   2   0   2   0   0 157   3]
 [  1   0   0   0   2   0   0   0   1 173]]


In [ ]:
df_actual_vs_pre["predictedKnn_5"]=np.array(predictedKnn_5)

In [ ]:
# Call  to the k_nearest_neighbors
# value of k = 1
trainStart = time.time()

predictedKnn_1 = k_nearest_neighbors(train_X,pd.DataFrame(train_Y), test_X, 1)

trainEnd = time.time()


print("Training time : ", trainEnd-trainStart)
df_actual_vs_pre["predicted_K1"]=np.array(predictedKnn_1)


accuracy = accuracy_metric(test_Y, predictedKnn_1)
print('Accuracy when k=1 : %s' % accuracy)

classsification_report=classification_report(pd.DataFrame(test_Y), predictedKnn_1)


print('Classification report : \n',classsification_report)

Training time :  2766.9445700645447
Accuracy when k=1 : 95.01743896362731
Classification report : 
              precision    recall  f1-score   support

          1       0.96      0.99      0.97       359
          2       1.00      0.97      0.98       264
          3       0.95      0.94      0.94       198
          4       0.93      0.90      0.92       166
          5       0.94      0.92      0.93       200
          6       0.92      0.92      0.92       160
          7       0.97      0.98      0.97       170
          8       0.94      0.95      0.95       147
          9       0.94      0.91      0.93       166
         10       0.91      0.97      0.94       177

avg / total       0.95      0.95      0.95      2007



In [60]:
cm_k1= confusion_matrix(test_Y, predictedKnn_1)  
print("Confusion Matrix for k=1 \n",cm_k1)

Confusion Matrix for k=1 
 [[354   0   2   0   0   0   1   1   0   1]
 [  0 257   0   0   4   0   2   1   0   0]
 [  5   0 186   1   1   1   0   2   2   0]
 [  2   0   1 150   0   9   0   1   1   2]
 [  0   1   1   0 184   1   2   2   1   8]
 [  2   0   2   4   0 147   0   0   3   2]
 [  0   0   2   0   1   1 166   0   0   0]
 [  0   0   1   1   3   0   0 140   1   1]
 [  4   0   1   5   1   1   0   0 151   3]
 [  1   0   0   0   1   0   0   2   1 172]]


In [ ]:
df_actual_vs_pre["predicted_K1"]=np.array(predictedKnn_1)

## Weighted KNN Algorithm

In [27]:
# sort neighbors in ascending order of distance from test row
# Input param : 
#    train_X - training feature data 
#    test_row - test data row
#    num_neighbors - number of neighbours 
# returns the list with id of training row and distance value in ascendning order of distance
def get_sorted_neighbors(train_X, test_row, num_neighbors):
    distances = list()
    for idx,train_row in enumerate(train_X):
        dist = euclidean_distance(test_row, train_row)
        distances.append((idx, dist))
    distances.sort(key=lambda tup: tup[1])
    return distances

In [28]:
import operator 

In [29]:
# Locate the most similar neighbors using weighted KNN approach
# In weighted KNN higher weight is given to the closer point
# the closest neighbours with ascending order of distance are retrived
# Only top K distances are considered by looping for k times because we want to find K neighbours 
# Weights dictionary will have a label as key and corrosponing weight as value
# weight is calculated by 1/(distance*distance) (closer point will have higher weight)
#  If that label is already present in the dictionary then new weight is added to it 
# Input param : 
#    train_X - training feature data 
#    train_Y - training label data
#    test_row - test data row
#    num_neighbors - number of neighbours 

# returns the label which has highest weight

def weightedKNN(train_X,train_Y, test_row, num_neighbors):
    neighbors = get_sorted_neighbors(train_X, test_row, num_neighbors)

    weights=dict()
    for idx in range(num_neighbors):
        
        key=train_Y.iloc[neighbors[idx][0]].values[0]  
        distance=neighbors[idx][1]
        
        if key in weights.keys():
            weight=weights[key]
            weight+=(1/(distance*distance))
            weights[key]=weight
        else:
            weights[key]=(1/(distance*distance))
            
    return max(weights.items(), key = operator.itemgetter(1))[0] 

In [30]:
# call to the weightedKNN

# This method performs weightedKNN algorithm 
# Iterate through allthe test data set and pass it to the weightedKNN method
# It gets the list of predicted values for all the test data set
# Input param : 
# train_X - training feature data 
# train_Y - training label data
# test_X- test data set
# num_neighbors - number of neighbours 

def Weighted_k_nearest_neighbors(train_X,train_Y, test_X, num_neighbors):
    predictions = list()
    for row in test_X:
        output = weightedKNN(train_X,train_Y, row, num_neighbors)
        predictions.append(output)
    return(predictions)



In [31]:
# Call  to the weighted k_nearest_neighbors
# value of k =5 
trainStart = time.time()

weightedKNNPred = Weighted_k_nearest_neighbors(train_X,pd.DataFrame(train_Y), test_X, 5)

trainEnd = time.time()

print("Training time : ", trainEnd-trainStart)
df_actual_vs_pre["weightedKNNPred"]=np.array(weightedKNNPred)


accuracy = accuracy_metric(test_Y, weightedKNNPred)
print('Accuracy when k=5 : %s' % accuracy)



classsification_report=classification_report(pd.DataFrame(test_Y), weightedKNNPred)


print('Classification report : \n',classsification_report)


Training time :  2172.234790086746
Accuracy when k=5 : 95.31639262580967
Classification report : 
              precision    recall  f1-score   support

          1       0.97      0.99      0.98       359
          2       0.99      0.98      0.98       264
          3       0.96      0.92      0.94       198
          4       0.96      0.91      0.93       166
          5       0.93      0.91      0.92       200
          6       0.93      0.93      0.93       160
          7       0.97      0.98      0.97       170
          8       0.95      0.95      0.95       147
          9       0.94      0.95      0.94       166
         10       0.90      0.98      0.94       177

avg / total       0.95      0.95      0.95      2007



In [61]:
cm_weightedKNN= confusion_matrix(test_Y, weightedKNNPred)  
print("Confusion Matrix for weighted KNN : \n",cm_weightedKNN)

Confusion Matrix for weighted KNN : 
 [[355   0   2   0   0   0   0   1   0   1]
 [  0 258   0   0   3   0   2   1   0   0]
 [  5   0 183   1   2   0   1   2   4   0]
 [  1   0   1 151   0   9   0   1   1   2]
 [  0   2   1   0 182   0   2   2   1  10]
 [  2   0   1   3   0 148   0   0   2   4]
 [  1   0   2   0   1   0 166   0   0   0]
 [  0   0   1   0   5   0   0 140   1   0]
 [  2   0   0   2   0   2   0   0 157   3]
 [  1   0   0   0   2   0   0   0   1 173]]


In [62]:
df_actual_vs_pre.head(30)

0  predicted_K1  weightedKNNPred  predicted_K3  predicted_K5
0   10            10               10            10            10
1    7             7                7             7             7
2    4             4                4             4             4
3    7             7                7             7             7
4    7             7                7             7             7
5    1             1                1             1             1
6    1             1                1             1             1
7    1             1                1             1             1
8    7             7                7             7             7
9   10            10               10            10            10
10   7             7                7             7             7
11   3             3                3             3             3
12   3             3                3             3             3
13   5             5                5             5             5
14   1             1                1             1             1
15   4             4                4             4             4
16   2             2                2             2             2
17   7             3                3             3             3
18  10            10               10            10            10
19   7             7                7             7             7
20   3             3                3             3             3
21   3             3                3             3             3
22   5             5                5             5             5
23  10            10               10            10            10
24   7             7                7             7             7
25   3             3                3             3             3
26   1             1                1             1             1
27   4             6                4             4             4
28   9             4                9             9             9
29   4             4                4             4             4