In [1]:
#Author : Sayali Kudale
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np
import scipy.io
import time
import seaborn as sns 
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier 
import warnings
from sklearn.metrics import classification_report, confusion_matrix 


In [2]:
warnings.simplefilter(action='ignore')

mat = scipy.io.loadmat('Data/USPS_all.mat')
df_features = pd.DataFrame(mat['fea'])
df_gnd = pd.DataFrame(mat['gnd'])

In [3]:
train_features= df_features.iloc[:7291] 
test_features= df_features.iloc[-2007:]
train_decisions= df_gnd.iloc[:7291] 
test_decisions= df_gnd.iloc[-2007:] 

In [4]:
sc_X = StandardScaler()
train_features = sc_X.fit_transform(train_features)
test_features = sc_X.transform(test_features)

In [5]:
knn = KNeighborsClassifier(n_neighbors = 1) 

trainStart = time.time()
knn.fit(train_features, train_decisions) 

trainEnd = time.time()

print("Training time : ", trainEnd-trainStart)


Training time :  0.21584796905517578


In [6]:
pred = knn.predict(test_features) 

In [7]:
confusionMatrix=confusion_matrix(test_decisions, pred)
print('confusion matrix : \n',confusionMatrix)


cr=classification_report(test_decisions,pred)
print('Classification report : \n',cr)

confusion matrix : 
 [[355   0   2   0   0   0   0   1   0   1]
 [  0 254   2   0   5   0   2   1   0   0]
 [  6   0 182   2   1   1   1   1   4   0]
 [  1   0   2 149   0   8   0   2   2   2]
 [  0   1   2   0 184   1   2   2   0   8]
 [  5   0   1   7   0 139   0   1   5   2]
 [  1   0   3   0   1   2 163   0   0   0]
 [  0   0   1   0   4   0   0 140   0   2]
 [  4   0   1   5   0   1   0   0 153   2]
 [  1   0   0   0   2   0   0   5   0 169]]
Classification report : 
              precision    recall  f1-score   support

          1       0.95      0.99      0.97       359
          2       1.00      0.96      0.98       264
          3       0.93      0.92      0.92       198
          4       0.91      0.90      0.91       166
          5       0.93      0.92      0.93       200
          6       0.91      0.87      0.89       160
          7       0.97      0.96      0.96       170
          8       0.92      0.95      0.93       147
          9       0.93      0.92      0.93  